version: '2'

services:
    database:
        image: postgres:9.6-alpine
        volumes:
            - /srv/docker/iix-notes/data/database:/var/lib/postgresql/data:Z
        environment:
            TZ: Europe/Stockholm
        restart: unless-stopped

    backend:
        image: loll3k/spark-backend
        environment:
            TZ: Europe/Stockholm
            IP: 0.0.0.0
            DBPATH: jdbc:postgresql://database:5432/iix-notes
            DBUSER: ${DB_USER}
            DBPASSWORD: ${DB_PASS}
            GOODREADS_KEY: ${GOODREADS_KEY}
            JWT: ${JWT}
        entrypoint: ["/bin/bash", "/app/init"]
        ports:
            - "127.0.0.1:8002:8002"
        restart: unless-stopped
 
    frontend:
        image: loll3k/iix.se-vue-frontend
        ports:
            - "127.0.0.1:8003:80"
        environment:
            TZ: Europe/Stockholm
        restart: unless-stopped

#   backend_new:
#       image: loll3k/iix.se-rust-backend
#       environment:
#           TZ: Europe/Stockholm
#           IP: 0.0.0.0
#           DBPATH: jdbc:postgresql://database:5432/iix-notes
#           DBUSER: ${DB_USER}
#           DBPASSWORD: ${DB_PASS}
#           GOODREADS_KEY: ${GOODREADS_KEY}
#           JWT: ${JWT}
#       ports:
#           - "127.0.0.1:8004:8080"
#       restart: unless-stopped

#   frontend_new:
#       image: loll3k/iix.se-vue-frontend
#       ports:
#           - "127.0.0.1:8005:80"
#       environment:
#           TZ: Europe/Stockholm
#       restart: unless-stopped


